version: '2'

services:
  dynamo:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - '8000:8000'
  init-dynamo:
    image: garland/aws-cli-docker
    command: 'aws dynamodb create-table --table-name video_streams --attribute-definitions AttributeName=userId,AttributeType=S AttributeName=videoStreamId,AttributeType=S --key-schema AttributeName=userId,KeyType=HASH AttributeName=videoStreamId,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --endpoint-url http://dynamo:8000'
    links:
      - dynamo
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=eu-west-2
